@startuml
participant ":FitLogger" as FL
participant ":Storage" as ST
participant ":Scanner" as SC

FL -> ST : loadData(profile)
ST -> ST : check if file exists
alt file does not exist
    ST --> FL : empty list
else file exists
    ST -> SC : new Scanner(file)
    ST -> ST : parseProfile(line 1, profile)
    loop for each remaining line
        ST -> SC : nextLine()
        ST --> FL : Workout object (R or L)
    end
end
@enduml
