@startuml
participant ":FitLogger" as FL
participant ":ExitCommand" as CMD
participant ":Storage" as ST
participant ":FileWriter" as FW

FL -> CMD : execute(storage, workouts, ui, profile)
CMD -> ST : saveData(workouts, profile)
ST -> ST : check/create data/ directory
ST -> FW : new FileWriter(file)
ST -> FW : write(profile.toFileFormat())
loop for each workout
    ST -> FW : write(workout.toFileFormat())
end
FW --> ST : close
ST --> CMD : true
CMD -> FL : showGoodbye()
@enduml
